# Generated by Django 5.1.2 on 2024-10-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'notes', 'verbose_name_plural': 'notes'},
        ),
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.TextField(default='default', max_length=200),
        ),
    ]
